name: Release
on:
  push:
    branches:
      - ${{ github.event.repository.default_branch }}

env:
  COMPOSER: "${GITHUB_WORKSPACE}/composer-release.json"

jobs:
  create_release:
    runs-on: "ubuntu-latest"
    name: "Create release"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"
      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "8.2"
          tools: composer:v2
      - name: "Install dependencies"
        run: "composer update --no-progress --prefer-dist"
      - name: "Pack phar"
        run: "php -d phar.readonly=false compiler/compiler.php"
      - name: Bump version and push tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: "Release"
        uses: softprops/action-hg-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: php-parser.phar
